pip install python-dotenv
pip install django
pip install django-cors-headers
pip install bs4
pip install django-request
pip install openai==0.28
pip install google
pip install transformers
pip install torch
pip install accelerate
pip install tensorflow